FROM @BASE_OS@

ARG installer=dnf
RUN ${installer} -y install \
        which git rpm-build \
        python3{,-devel,-pip,-rpm,-koji,-dnf,-createrepo_c}
RUN python3 -m pip install pipenv

WORKDIR /code
COPY . .
RUN pipenv install --three --system --deploy --dev
CMD ["/usr/bin/python3", "setup.py", "test"]
