FROM @BASE_OS@

    # Createrepo_c
ENV SYSTEM_DEPS="git rpm-build python3-devel python3-pip python3-rpm python3-koji python3-dnf python3-createrepo_c"

WORKDIR /code
COPY . .
RUN dnf --assumeyes install $BUILD_DEPS $SYSTEM_DEPS \
    && python3 -m pip install --user --editable .[dev]
CMD ["/usr/bin/python3", "setup.py", "test"]
